version: "3.8"

services:
  app:
    container_name: node-docker-app
    build: .
    ports:
      - "4000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: always
